version: '3.9'

services:
  db:
    image: postgres:14.3
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '9785'
      POSTGRES_DB: 'start_wars'